name: Android App Build

on:
  push:
    branches: ["master"]
    paths:
      - 'app/**'
      - '.github/workflows/builda-app.yml'
  pull_request:
    branches: ["master"]
    paths:
      - 'app/**'

jobs:
  build:
    name: Build the Signsense Android app
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test
